version: "3"
services:
  app:
    build: .
    working_dir: /app
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules
  postgres:
    image: postgres
    container_name: "db"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
